import {
  Users, LayoutGrid, Plus, Edit, Trash2, LogOut, Eye, EyeOff, Home,
  X, Search, ChevronUp, ChevronDown, Settings, Columns, List,
  Paperclip, Download, MessageSquare, Move, Check, Lock, SlidersHorizontal,
  Globe, Copy, ExternalLink, Calculator, Database, Loader2, Package,
  AlertCircle, ShieldCheck, RefreshCw, BarChart2, Play, Filter,
} from 'lucide-react';

export const Icons = {
  users: Users,
  board: LayoutGrid,
  plus: Plus,
  edit: Edit,
  trash: Trash2,
  logout: LogOut,
  eye: Eye,
  eyeOff: EyeOff,
  home: Home,
  x: X,
  search: Search,
  up: ChevronUp,
  down: ChevronDown,
  settings: Settings,
  columns: Columns,
  list: List,
  clip: Paperclip,
  dl: Download,
  msg: MessageSquare,
  move: Move,
  check: Check,
  lock: Lock,
  fields: SlidersHorizontal,
  globe: Globe,
  copy: Copy,
  externalLink: ExternalLink,
  formula: Calculator,
  sap: Database,
  spinner: Loader2,
  package: Package,
  alert: AlertCircle,
  shield: ShieldCheck,
  sync: RefreshCw,
  reports: BarChart2,
  play: Play,
  filter: Filter,
};
